version: '3.7'
services:
  ingress:
    image: nginx
    container_name: ingress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 7000:80

  instance-01:
    image: node:18-alpine
    container_name: instance-01
    working_dir: /usr/apps/example
    environment:
      - INSTANCE_NAME=instance-01
    volumes:
      - .:/usr/apps/example
    ports:
      - 7001:7000
    command: npm run start

  instance-02:
    image: node:18-alpine
    container_name: instance-02
    working_dir: /usr/apps/example
    environment:
      - INSTANCE_NAME=instance-02
    volumes:
      - .:/usr/apps/example
    ports:
      - 7002:7000
    command: npm run start

  instance-03:
    image: node:18-alpine
    container_name: instance-03
    working_dir: /usr/apps/example
    environment:
      - INSTANCE_NAME=instance-03
    volumes:
      - .:/usr/apps/example
    ports:
      - 7003:7000
    command: npm run start